In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/home/sam/Desktop/samlab/codes/DataScience/datasets/Churn_Modelling.csv')

from sklearn import datasets
df = datasets.load_iris()

In [3]:
# # preprocessing
# df.drop(['Surname'], axis =1, inplace = True) # remove unwanted columns

In [4]:
# x = df.iloc[:,:-1]
# y = df.iloc[:,-1]
# x = pd.get_dummies(x, drop_first = True)

# another data
x = df.data
y = df.target

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.5, random_state = 0)

In [6]:
# Build Model
from sklearn.linear_model import LogisticRegression
Logregg = LogisticRegression(random_state = 42).fit(x_train, y_train)
prediction = Logregg.predict(x_test)

from sklearn.metrics import accuracy_score, confusion_matrix
acc = accuracy_score(prediction, y_test)
mat = confusion_matrix(prediction, y_test)
print(acc)
print('----------')
print(mat)

0.9333333333333333
----------
[[21  0  0]
 [ 0 29  4]
 [ 0  1 20]]


In [7]:
# Build Model
from sklearn.tree import DecisionTreeClassifier
Logregg = DecisionTreeClassifier(random_state = 42)
Logregg.fit(x_train, y_train)
prediction = Logregg.predict(x_test)

from sklearn.metrics import accuracy_score, confusion_matrix
acc = accuracy_score(prediction, y_test)
mat = confusion_matrix(y_test, prediction)
print(acc)
print('----------')
print(mat)

0.96
----------
[[21  0  0]
 [ 0 29  1]
 [ 0  2 22]]


In [8]:
# Build Model
from sklearn.ensemble import RandomForestClassifier
Logregg = RandomForestClassifier(random_state = 21)
Logregg.fit(x_train, y_train)
prediction = Logregg.predict(x_test)

from sklearn.metrics import accuracy_score, confusion_matrix
acc = accuracy_score(prediction, y_test)
mat = confusion_matrix(prediction, y_test)
print(acc)
print('---
      --r-----')

SyntaxError: EOL while scanning string literal (<ipython-input-8-9a24a4f24ba4>, line 11)

In [ ]:
# Build Model
from sklearn.neighbors import KNeighborsClassifier
Logregg = KNeighborsClassifier()
Logregg.fit(x_train, y_train)
prediction = Logregg.predict(x_test)

from sklearn.metrics import accuracy_score, confusion_matrix
acc = accuracy_score(prediction, y_test)
mat = confusion_matrix(prediction, y_test)
print(acc)
print('-----r-----')
print(mat)

In [ ]:
# Build Model
from sklearn.linear_model import SGDClassifier
Logregg = SGDClassifier(loss="hinge", penalty="l1", max_iter=19
                    )
Logregg.fit(x_train, y_train)
prediction = Logregg.predict(x_test)

from sklearn.metrics import accuracy_score, confusion_matrix
acc = accuracy_score(prediction, y_test)
mat = confusion_matrix(prediction, y_test)
print(acc)
print('-----r-----')
print(mat)

In [ ]:
import tensorflow.keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

Ann = Sequential()
Ann.add(Dense(6, input_dim=4, kernel_initializer='he_uniform', activation='softmax'))
Ann.add(Dense(1, activation = 'sigmoid'))
Ann.compile(optimizer = 'sgd', loss='binary_crossentropy', metrics=['accuracy'])
Ann.fit(x_train, y_train, batch_size = 10, epochs = 1000)

Epoch 1/1000
75/75 [==============================] - 0s 1ms/sample - loss: 0.6472 - acc: 0.2667
Epoch 2/1000
75/75 [==============================] - 0s 201us/sample - loss: 0.6247 - acc: 0.2667
Epoch 3/1000
75/75 [==============================] - 0s 224us/sample - loss: 0.6019 - acc: 0.2667
Epoch 4/1000
75/75 [==============================] - 0s 230us/sample - loss: 0.5808 - acc: 0.2667
Epoch 5/1000
75/75 [==============================] - 0s 211us/sample - loss: 0.5621 - acc: 0.2667
Epoch 6/1000
75/75 [==============================] - 0s 218us/sample - loss: 0.5462 - acc: 0.2667
Epoch 7/1000
75/75 [==============================] - 0s 232us/sample - loss: 0.5298 - acc: 0.2667
Epoch 8/1000
75/75 [==============================] - 0s 214us/sample - loss: 0.5141 - acc: 0.2667
Epoch 9/1000
75/75 [==============================] - 0s 226us/sample - loss: 0.5000 - acc: 0.2667
Epoch 10/1000
75/75 [==============================] - 0s 226us/sample - loss: 0.4864 - acc: 0.2667
Epoch 11/10

75/75 [==============================] - 0s 234us/sample - loss: 0.1981 - acc: 0.2667
Epoch 84/1000
75/75 [==============================] - 0s 204us/sample - loss: 0.1978 - acc: 0.2667
Epoch 85/1000
75/75 [==============================] - 0s 222us/sample - loss: 0.1973 - acc: 0.2667
Epoch 86/1000
75/75 [==============================] - 0s 188us/sample - loss: 0.1968 - acc: 0.2667
Epoch 87/1000
75/75 [==============================] - 0s 209us/sample - loss: 0.1959 - acc: 0.2667
Epoch 88/1000
75/75 [==============================] - 0s 185us/sample - loss: 0.1953 - acc: 0.2667
Epoch 89/1000
75/75 [==============================] - 0s 197us/sample - loss: 0.1947 - acc: 0.2667
Epoch 90/1000
75/75 [==============================] - 0s 207us/sample - loss: 0.1942 - acc: 0.2667
Epoch 91/1000
75/75 [==============================] - 0s 195us/sample - loss: 0.1932 - acc: 0.2667
Epoch 92/1000
75/75 [==============================] - 0s 201us/sample - loss: 0.1940 - acc: 0.2667
Epoch 93/1000


In [34]:
import numpy as np
prediction = Ann.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, mean_squared_error
mat = mean_squared_error(prediction, y_test)
mat